<?php

declare(strict_types=1);

/**
 * Error vocabulary shared by inventory pulls and credential connection tests.
 * The stored code names the repair side; only an ESXi login rejection pauses
 * an ESXi credential. The VARCHAR remains deliberately open for legacy rows.
 */
const VIRTUSPHERE_INVENTORY_ERROR_DNS = 'dns';
const VIRTUSPHERE_INVENTORY_ERROR_UNREACHABLE = 'unreachable';
const VIRTUSPHERE_INVENTORY_ERROR_CERTIFICATE = 'certificate';
const VIRTUSPHERE_INVENTORY_ERROR_TLS = 'tls';
const VIRTUSPHERE_INVENTORY_ERROR_AUTH = 'auth';
const VIRTUSPHERE_INVENTORY_ERROR_AUTHZ = 'authz';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_DNS = 'ansible_dns';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_UNREACHABLE = 'ansible_unreachable';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_AUTH = 'ansible_auth';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_AUTHZ = 'ansible_authz';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_PREFLIGHT = 'ansible_preflight';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_CONFIG = 'ansible_config';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_SFTP = 'ansible_sftp';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_TIMEOUT = 'ansible_timeout';
const VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_TRANSPORT = 'ansible_transport';
const VIRTUSPHERE_INVENTORY_ERROR_HTTP = 'http';
const VIRTUSPHERE_INVENTORY_ERROR_SSH = 'ssh';
const VIRTUSPHERE_INVENTORY_ERROR_WORKER = 'worker';
const VIRTUSPHERE_INVENTORY_ERROR_PARSE = 'parse';
const VIRTUSPHERE_INVENTORY_ERROR_CONFIG = 'config';
const VIRTUSPHERE_INVENTORY_ERROR_CATEGORIES = [
    VIRTUSPHERE_INVENTORY_ERROR_DNS,
    VIRTUSPHERE_INVENTORY_ERROR_UNREACHABLE,
    VIRTUSPHERE_INVENTORY_ERROR_CERTIFICATE,
    VIRTUSPHERE_INVENTORY_ERROR_TLS,
    VIRTUSPHERE_INVENTORY_ERROR_AUTH,
    VIRTUSPHERE_INVENTORY_ERROR_AUTHZ,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_DNS,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_UNREACHABLE,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_AUTH,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_AUTHZ,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_PREFLIGHT,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_CONFIG,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_SFTP,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_TIMEOUT,
    VIRTUSPHERE_INVENTORY_ERROR_ANSIBLE_TRANSPORT,
    VIRTUSPHERE_INVENTORY_ERROR_HTTP,
    VIRTUSPHERE_INVENTORY_ERROR_SSH,
    VIRTUSPHERE_INVENTORY_ERROR_WORKER,
    VIRTUSPHERE_INVENTORY_ERROR_PARSE,
    VIRTUSPHERE_INVENTORY_ERROR_CONFIG,
];

function inventory_error_is_ansible(string $category): bool
{
    return str_starts_with($category, 'ansible_')
        && in_array($category, VIRTUSPHERE_INVENTORY_ERROR_CATEGORIES, true);
}
function inventory_error_pauses_credential(string $category): bool
{
    return $category === VIRTUSPHERE_INVENTORY_ERROR_AUTH;
}
