<?php

declare(strict_types=1);

const VIRTUSPHERE_REMOTE_PROTOCOL_VERSION = 1;

const VIRTUSPHERE_EXECUTION_CONTRACT_LEGACY = 'legacy_v1';
const VIRTUSPHERE_EXECUTION_CONTRACT_REMOTE = 'remote_v1';
const VIRTUSPHERE_EXECUTION_CONTRACTS = [
    VIRTUSPHERE_EXECUTION_CONTRACT_LEGACY,
    VIRTUSPHERE_EXECUTION_CONTRACT_REMOTE,
];

const VIRTUSPHERE_REMOTE_ACTIVATION_DISABLED = 'disabled';
const VIRTUSPHERE_REMOTE_ACTIVATION_LEGACY = 'legacy_explicit';
const VIRTUSPHERE_REMOTE_ACTIVATION_PILOT = 'pilot_remote';
const VIRTUSPHERE_REMOTE_ACTIVATION_ENABLED = 'remote_enabled';
const VIRTUSPHERE_REMOTE_ACTIVATION_ROLLBACK = 'rollback_pending';
const VIRTUSPHERE_REMOTE_ACTIVATION_STATES = [
    VIRTUSPHERE_REMOTE_ACTIVATION_DISABLED,
    VIRTUSPHERE_REMOTE_ACTIVATION_LEGACY,
    VIRTUSPHERE_REMOTE_ACTIVATION_PILOT,
    VIRTUSPHERE_REMOTE_ACTIVATION_ENABLED,
    VIRTUSPHERE_REMOTE_ACTIVATION_ROLLBACK,
];

const VIRTUSPHERE_SUPERVISOR_CONTRACT_WORKER = 'worker_v1';
const VIRTUSPHERE_SUPERVISOR_CONTRACT_SUPERVISOR = 'supervisor_v1';
const VIRTUSPHERE_SUPERVISOR_CONTRACTS = [
    VIRTUSPHERE_SUPERVISOR_CONTRACT_WORKER,
    VIRTUSPHERE_SUPERVISOR_CONTRACT_SUPERVISOR,
];

const VIRTUSPHERE_RUNTIME_ROTATION_INSTALL = 'install';
const VIRTUSPHERE_RUNTIME_ROTATION_RESTORE = 'restore';
const VIRTUSPHERE_RUNTIME_ROTATION_CLONE = 'clone';
const VIRTUSPHERE_RUNTIME_ROTATION_REASONS = [
    VIRTUSPHERE_RUNTIME_ROTATION_INSTALL,
    VIRTUSPHERE_RUNTIME_ROTATION_RESTORE,
    VIRTUSPHERE_RUNTIME_ROTATION_CLONE,
];

const VIRTUSPHERE_DEPLOY_RECOVERY_REMOTE_OBSERVATION = 'remote_observation';
const VIRTUSPHERE_DEPLOY_RECOVERY_LEGACY_UNCERTAIN = 'legacy_uncertain';
const VIRTUSPHERE_DEPLOY_RECOVERY_FOREIGN_GENERATION = 'foreign_generation';
const VIRTUSPHERE_DEPLOY_RECOVERY_REASONS = [
    VIRTUSPHERE_DEPLOY_RECOVERY_REMOTE_OBSERVATION,
    VIRTUSPHERE_DEPLOY_RECOVERY_LEGACY_UNCERTAIN,
    VIRTUSPHERE_DEPLOY_RECOVERY_FOREIGN_GENERATION,
];

const VIRTUSPHERE_REMOTE_CONTROLLER_STATES = [
    'prepared', 'active', 'exited_0', 'exited_nonzero', 'exited_signal',
    'lost_after_start', 'never_started', 'protocol_error',
];
const VIRTUSPHERE_REMOTE_EFFECT_STATES = ['not_started', 'active_or_possible', 'goal_verified', 'divergence_verified', 'unknown'];
const VIRTUSPHERE_REMOTE_RECONCILIATION_STATES = ['not_required', 'pending', 'running', 'resolved_success', 'resolved_failure', 'manual_required'];
const VIRTUSPHERE_REMOTE_CLEANUP_STATES = ['pending', 'eligible', 'running', 'cleaned', 'failed'];

const VIRTUSPHERE_REMOTE_PROTOCOL_DOCUMENT_MAX_BYTES = 65536;
const VIRTUSPHERE_REMOTE_OUTPUT_CHUNK_MAX_BYTES = 1048576;
const VIRTUSPHERE_REMOTE_OBSERVATION_MAX_BYTES = 1468000;

const VIRTUSPHERE_DEPLOY_WORKER_LEASE_NAME = 'deploy-worker';
