<?php

declare(strict_types=1);

return [
    'packages_heading' => 'Packages & versions',
    'packages_p1' => 'Packages are not created in the portal but on the MECM server. There the autoimporter reads every package folder with its config.json (required fields ProjectName and version) and builds an MECM application including a device collection. Its name is composed from both fields: ProjectName, a hyphen, then the version, for example "Firefox-115.0". The package sync reports exactly these collection names via HTTP to the portal, which only displays the catalog and links packages to VMs.',
    'packages_p1b' => 'The portal reverses this composition to show base name and version separately and to keep multiple versions of the same package distinguishable. It splits at the last hyphen: everything before it is the base name, everything after it is the version. This is necessary because the base name itself may contain hyphens (such as "Adobe-Reader-DC") while the version may not. Only under this rule is the last hyphen unambiguously the boundary between name and version. For package maintenance on the MECM server this means: in config.json the version must not contain a hyphen, while the ProjectName may.',
    'packages_p2' => 'If a package disappears from MECM it is not deleted but marked as "Retired"; existing VM assignments are kept. An assignment is relinked only on a real version bump, that is when the same sync brings a newly appearing higher version of that package. If a package is merely missing for a while, because MECM is not answering or somebody is working in it, the assignment stays untouched: the package is retired, still visible in the VM editor, and a note names the newer version available. So a human always decides which version a VM gets.',
    'packages_p2b' => 'Retired packages are removed for good after :days days, but only those that were never assigned to a VM. A row whose assignments were once relinked to a successor is kept permanently; otherwise a VM\'s history would become untraceable once the cleanup window passed.',
    'packages_p3' => 'The package list can be filtered by status (Active/Retired). The VM editor hides retired packages; if a VM is still linked to a retired version it stays visible and a hint shows the newer version that is available.',
    'packages_os_heading' => 'Operating systems',
    'packages_os_p1' => 'Like packages, operating systems are not maintained in the portal; they come from MECM. The same package sync also reports every Task Sequence on the MECM server, and from these the operating system catalog is built, which the "Operating Systems" page displays. An entry is only effective when its name matches a Task Sequence exactly, because the operating system assigned to a VM selects that Task Sequence for the PXE boot. That is why entries cannot be created or edited here: a hand-typed name without a matching Task Sequence would point nowhere at PXE boot.',
    'packages_os_p2' => 'New Task Sequences appear automatically on the next sync (default cadence 60 seconds, plus a full reconciliation every hour). When a Task Sequence is deleted in MECM, the entry does not disappear but becomes "Retired"; assigned VMs keep their choice, and the entry is only removed after :days days once no VM still uses it. An administrator can also delete an entry by hand: if the Task Sequence still exists in MECM, the next sync re-creates it (self-healing); if the sync is down (MECM outage), it stays missing until it returns, without harming existing VMs, whose assignment uses the stored name. If all Task Sequences are removed or MECM currently returns none, the catalog stays unchanged instead of being emptied.',
];
