<?php

declare(strict_types=1);

return [
    'packages_heading' => 'Pakete & Versionen',
    'packages_p1' => 'Pakete werden nicht im Portal angelegt, sondern auf dem MECM-Server. Dort liest der Autoimporter jeden Paketordner mit seiner config.json (Pflichtfelder ProjectName und version) und baut daraus eine MECM-Anwendung samt Device-Collection. Deren Name entsteht aus beiden Feldern zusammengesetzt: ProjectName, ein Bindestrich, dann die Version, zum Beispiel „Firefox-115.0". Der Paket-Sync meldet genau diese Collection-Namen per HTTP an das Portal, das den Katalog nur anzeigt und Pakete mit VMs verknüpft.',
    'packages_p1b' => 'Das Portal dreht diese Zusammensetzung wieder auf, um Basisname und Version getrennt anzuzeigen und mehrere Versionen desselben Pakets unterscheidbar zu machen. Getrennt wird am letzten Bindestrich: alles davor ist der Basisname, alles danach die Version. Das ist nötig, weil der Basisname selbst Bindestriche enthalten darf (etwa „Adobe-Reader-DC"), die Version dagegen nicht. Nur unter dieser Regel ist der letzte Bindestrich eindeutig die Grenze zwischen Name und Version. Für die Paketpflege auf dem MECM-Server heißt das: In der config.json darf die version keinen Bindestrich enthalten, der ProjectName dagegen schon.',
    'packages_p2' => 'Verschwindet ein Paket aus MECM, wird es nicht gelöscht, sondern als „Zurückgezogen" markiert; bestehende VM-Zuordnungen bleiben erhalten. Umgehängt wird eine Zuordnung nur bei einem echten Versionssprung, also wenn im selben Abgleich eine höhere Version dieses Pakets neu dazukommt. Fehlt ein Paket bloß vorübergehend, etwa weil MECM gerade nicht antwortet oder jemand dort arbeitet, bleibt die Zuordnung unangetastet: das Paket ist dann zurückgezogen, im VM-Editor weiter sichtbar, und ein Hinweis nennt die verfügbare neuere Version. So entscheidet immer ein Mensch, welche Version eine VM bekommt.',
    'packages_p2b' => 'Zurückgezogene Pakete werden nach :days Tagen endgültig entfernt, aber nur solche, die nie einer VM zugeordnet waren. Eine Zeile, deren Zuordnungen einmal auf eine Nachfolgeversion umgehängt wurden, bleibt dauerhaft erhalten; sonst wäre die Vorgeschichte einer VM nach der Aufräumfrist nicht mehr nachvollziehbar.',
    'packages_p3' => 'Die Paketliste lässt sich nach Status (Aktiv/Zurückgezogen) filtern. Im VM-Editor werden zurückgezogene Pakete ausgeblendet; ist eine VM noch mit einer zurückgezogenen Version verknüpft, bleibt diese sichtbar und ein Hinweis zeigt die verfügbare neuere Version.',
    'packages_os_heading' => 'Betriebssysteme',
    'packages_os_p1' => 'Betriebssysteme werden wie Pakete nicht im Portal gepflegt, sondern kommen aus MECM. Derselbe Paket-Sync meldet zusätzlich jede Task Sequence des MECM-Servers; daraus entsteht der Betriebssystem-Katalog, den die Seite „Betriebssysteme" anzeigt. Ein Eintrag wirkt nur, wenn sein Name exakt einer Task Sequence entspricht, denn die Betriebssystem-Zuordnung einer VM wählt genau diese Task Sequence für den PXE-Boot. Deshalb lassen sich Einträge hier nicht anlegen oder bearbeiten: Ein von Hand getippter Name ohne passende Task Sequence würde beim PXE-Boot ins Leere zeigen.',
    'packages_os_p2' => 'Neue Task Sequences erscheinen automatisch beim nächsten Sync (Standardtakt 60 Sekunden, zusätzlich stündlich ein voller Abgleich). Wird eine Task Sequence in MECM gelöscht, verschwindet der Eintrag nicht, sondern wird „Zurückgezogen"; zugeordnete VMs behalten ihre Auswahl, und der Eintrag wird erst nach :days Tagen entfernt, sofern keine VM ihn mehr nutzt. Ein Administrator kann einen Eintrag zusätzlich von Hand löschen: Existiert die Task Sequence noch in MECM, legt der nächste Sync ihn wieder an (Selbstheilung); steht der Sync gerade (MECM-Ausfall), fehlt er bis zur Rückkehr, ohne dass bestehende VMs Schaden nehmen, da deren Zuordnung den gespeicherten Namen nutzt. Werden alle Task Sequences entfernt oder liefert MECM gerade keine, bleibt der Katalog unverändert stehen, statt geleert zu werden.',
];
